$schema: https://vecorel.github.io/sdl/v0.1.0/schema.json
required:
  - schemas
  - id
  - collection
  - geometry
collection:
  schemas: true
  id: false
  geometry: false
  bbox: false
properties:
  schemas:
    type: array
    items:
      type: string
      format: uri
      pattern: ^https?://
    contains:
      type: string
      enum:
        - https://vecorel.github.io/specification/v0.1.0/schema.yaml
  id:
    type: string
    minLength: 1
  collection:
    type: string
    minLength: 1
  geometry:
    type: geometry
  bbox:
    type: bounding-box
